development:
  adapter: postgresql
  database: hugesin_development
  encoding: unicode
  username: hugh
  password: ""

test:
  adapter: postgresql
  database: hugesin_test
  encoding: unicode
  username: hugh
  password: ""

production:
  adapter: postgresql
  database: hugh_production
  encoding: unicode
  username: hugh
  password: ""
