development:
  adapter: postgresql
  database: calenshare_development
  encoding: unicode
  username: calenshare
  password: ""

test:
  adapter: postgresql
  database: calenshare_test
  encoding: unicode
  username: calenshare
  password: ""

production:
  adapter: postgresql
  database: calenshare_production
  encoding: unicode
  username: calenshare
  password: ""
