class AddMoreCities < ActiveRecord::Migration
  def change
  	#US CITIES

		City.create(name: 'Louisville, Kentucky', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Albuquerque, New Mexico', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Tucson, Arizona', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Fresno, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Sacramento, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Long Beach, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Mesa, Arizona', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Virginia Beach, Virginia', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Colorado Springs, Colorado', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Raleigh, North Carolina', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Omaha, Nebraska', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Tulsa, Oklahoma', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Oakland, California', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Cleveland, Ohio', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Wichita, Kansas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Arlington, Texas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Bakersfield, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Tampa, Florida', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Anaheim, California', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Honolulu, Hawaii', timezone: 'Hawaii')
		City.create(name: 'Aurora, Colorado', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Santa Ana, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'St. Louis, Missouri', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Riverside, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Corpus Christi, Texas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Lexington, Kentucky', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Stockton, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Cincinnati, Ohio', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Anchorage, Alaska', timezone: 'Alaska')
		City.create(name: 'Saint Paul, Minnesota', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Toledo, Ohio', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Newark, New Jersey', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Greensboro, North Carolina', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Plano, Texas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Lincoln, Nebraska', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Buffalo, New York', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Henderson, Nevada', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Fort Wayne, Indiana', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Jersey City, New Jersey', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Chula Vista, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Saint Petersburg, Florida', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Orlando, Florida', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Norfolk, Virginia', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Laredo, Texas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Chandler, Arizona', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Lubbock, Texas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Durham, North Carolina', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Winston Salem, North Carolina', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Garland, Texas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Glendale, Arizona', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Baton Rouge, Louisiana', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Hialeah, Florida', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Reno, Nevada', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Chesapeake, Virginia', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Scottsdale, Arizona', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Irving, Texas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'North Las Vegas, Nevada', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Fremont, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Irvine, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'San Bernardino, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Birmingham, Alabama', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Gilbert, Arizona', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Rochester, New York', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Boise , Idaho', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Spokane, Washington', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Montgomery, Alabama', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Des Moines, Iowa', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Richmond, Virginia', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Fayetteville, North Carolina', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Modesto, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Shreveport, Louisiana', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Tacoma, Washington', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Oxnard, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Aurora, Illinois', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Fontana, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Akron, Ohio', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Moreno Valley, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Yonkers, New York', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Augusta, Georgia', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Little Rock, Arkansas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Mobile, Alabama', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Columbus, Georgia', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Amarillo, Texas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Glendale, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Huntington Beach, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Grand Rapids, Michigan', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Tallahassee, Florida', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Huntsville, Alabama', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Worcester, Massachusetts', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Knoxville, Tennessee', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Newport News, Virginia', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Grand Prairie, Texas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Brownsville, Texas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Providence, Rhode Island', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Santa Clarita, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Overland Park, Kansas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Jackson, Mississippi', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Garden Grove, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Chattanooga, Tennessee', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Oceanside, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Santa Rosa, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Fort Lauderdale, Florida', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Rancho Cucamonga, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Ontario, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Port Saint Lucie, Florida', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Vancouver, Washington', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Tempe, Arizona', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Springfield, Missouri', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Lancaster, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Pembroke Pines, Florida', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Cape Coral, Florida', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Eugene, Oregon', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Peoria, Arizona', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Sioux Falls, South Dakota', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Salem, Oregon', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Corona, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Elk Grove, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Palmdale, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Springfield, Massachusetts', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Salinas, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Pasadena, Texas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Rockford, Illinois', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Pomona, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Joliet, Illinois', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Fort Collins, Colorado', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Torrance, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Kansas City, Kansas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Paterson, New Jersey', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Hayward, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Escondido, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Bridgeport, Connecticut', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Syracuse, New York', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Lakewood, Colorado', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Alexandria, Virginia', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Hollywood, Florida', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Naperville, Illinois', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Mesquite, Texas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Sunnyvale, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Dayton, Ohio', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Cary, North Carolina', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Savannah, Georgia', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Orange, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Pasadena, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Fullerton, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Hampton, Virginia', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Clarksville, Tennessee', timezone: 'Central Time (US & Canada)')
		City.create(name: 'McKinney, Texas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Warren, Michigan', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'McAllen, Texas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'West Valley City, Utah', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Columbia, South Carolina', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Killeen, Texas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Sterling Heights, Michigan', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'New Haven, Connecticut', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Topeka, Kansas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Thousand Oaks, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Olathe, Kansas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Cedar Rapids, Iowa', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Waco, Texas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Visalia, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Elizabeth, New Jersey', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Simi Valley, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Gainesville, Florida', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Hartford, Connecticut', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Bellevue, Washington', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Miramar, Florida', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Concord, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Stamford, Connecticut', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Coral Springs, Florida', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Charleston, South Carolina', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Carrollton, Texas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Lafayette, Louisiana', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Roseville, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Thornton, Colorado', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Frisco, Texas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Kent, Washington', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Surprise, Arizona', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Allentown, Pennsylvania', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Beaumont, Texas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Santa Clara, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Abilene, Texas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Evansville, Indiana', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Victorville, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Independence, Missouri', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Denton, Texas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Springfield, Illinois', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Vallejo, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Athens, Georgia', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Provo, Utah', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Peoria, Illinois', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Ann Arbor, Michigan', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Lansing, Michigan', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'El Monte, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Midland, Texas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Berkeley, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Norman, Oklahoma', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Downey, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Costa Mesa, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Murfreesboro, Tennessee', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Inglewood, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Columbia, Missouri', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Waterbury, Connecticut', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Manchester, New Hampshire', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Miami Gardens, Florida', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Elgin, Illinois', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Wilmington, North Carolina', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Westminster, Colorado', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Rochester, Minnesota', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Clearwater, Florida', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Lowell, Massachusetts', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Pueblo, Colorado', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Arvada, Colorado', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Ventura, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Gresham, Oregon', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Fargo, North Dakota', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Carlsbad, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'West Covina, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Norwalk, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Fairfield, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Cambridge, Massachusetts', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Murrieta, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Green Bay, Wisconsin', timezone: 'Central Time (US & Canada)')
		City.create(name: 'High Point, North Carolina', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'West Jordan, Utah', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Billings, Montana', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Richmond, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Round Rock, Texas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Everett, Washington', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Burbank, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Antioch, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Wichita Falls, Texas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Palm Bay, Florida', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Centennial, Colorado', timezone: 'Mountain Time (US & Canada)')
		City.create(name: 'Temecula, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Daly City, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Odessa, Texas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Erie, Pennsylvania', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Richardson, Texas', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Pompano Beach, Florida', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'Flint, Michigan', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'South Bend, Indiana', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'West Palm Beach, Florida', timezone: 'Eastern Time (US & Canada)')
		City.create(name: 'El Cajon, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Davenport, Iowa', timezone: 'Central Time (US & Canada)')
		City.create(name: 'Rialto, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Santa Maria, California', timezone: 'Pacific Time (US & Canada)')
		City.create(name: 'Broken Arrow, Oklahoma', timezone: 'Central Time (US & Canada)')

		City.create(name: 'Sydney, Australia', timezone: 'Sydney')
		City.create(name: 'Melbourne, Australia', timezone: 'Sydney')
		City.create(name: 'Brisbane, Australia', timezone: 'Sydney')
		City.create(name: 'Gold Coast, Australia', timezone: 'Sydney')
		City.create(name: 'Newcastle, Australia', timezone: 'Sydney')
		City.create(name: 'Canberra, Australia', timezone: 'Sydney')
		City.create(name: 'Wollongong, Australia', timezone: 'Sydney')
		City.create(name: 'Sunshine Coast, Australia', timezone: 'Sydney')
		City.create(name: 'Hobart, Australia', timezone: 'Sydney')
		City.create(name: 'Geelong, Australia', timezone: 'Sydney')
		City.create(name: 'Townsville, Australia', timezone: 'Sydney')
		City.create(name: 'Cairns, Australia', timezone: 'Sydney')
		City.create(name: 'Perth, Australia', timezone: 'Hong Kong')
		City.create(name: 'Adelaide, Australia', timezone: 'Adelaide')
		City.create(name: 'Darwin, Australia', timezone: 'Adelaide')

		City.create(name: 'Hong Kong, China', timezone: 'Hong Kong')
		City.create(name: 'Beijing, China', timezone: 'Hong Kong')
		City.create(name: 'Taipei, Taiwan', timezone: 'Hong Kong')
		City.create(name: 'Shanghai, China', timezone: 'Hong Kong')
  end
end
